name: base

on:
  workflow_call:
    inputs:
      env:
        type: choice
        required: true
        options:
          - dev
          - prod
      auto:
        type: boolean
        required: true
      pod:
        type: boolean
        required: false

env:
  ENV: ${{ inputs.env }}
  AUTO: ${{ inputs.auto }}
  POD: ${{ inputs.pod }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - run: |
      echo "ENV: $ENV"
      echo "AUTO: $AUTO"
      echo "POD: $POD"
