name: base

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      auto:
        type: boolean
        required: true
      pod:
        type: boolean
        required: false
    secrets:
      TOKEN:
        type: string
        required: true


runs:
  using: "composite"
  steps:
    - name: echo
      run: |
        echo "AUTO: ${{ inputs.auto }}"
        echo "POD: ${{ inputs.pod }}"
        echo "ENV: ${{ inputs.env }}"
        echo "TOKEN: ${{ secrets.TOKEN }}"
        echo "VAL: ${{vars.VAL}}"
      shell: bash
