name: base


runs:
  using: "composite"
  steps:
    - name: echo
      run: |
        echo "AUTO: ${{ inputs.auto }}"
        echo "POD: ${{ inputs.pod }}"
        echo "ENV: ${{ inputs.env }}"
        echo "TOKEN: ${{ inputs.TOKEN }}"
        echo "VAL: ${{inputs.VAL}}"
      shell: bash
    - name: test secrets
      run: echo secret "${{inputs.TOKEN }}" | sed 's/./& /g'
      shell: bash

