name: base

on:
  workflow_call:
    inputs:
      env:
        type: choice
        required: true
        options:
          - dev
          - prod
      auto:
        type: boolean
        required: true
      pod:
        type: boolean
        required: false

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - run: |
      echo "ENV: $env.env"
      echo "AUTO: $env.auto"
      echo "POD: $env.pod"
      shell: bash 
