name: base

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      auto:
        type: boolean
        required: true
      pod:
        type: boolean
        required: false
      TOKEN:
        type: string
        required: true
      VAL:
        type: string
        required: true

runs:
  using: "composite"
  steps:
    - name: echo
      run: |
        echo "AUTO: ${{ inputs.auto }}"
        echo "POD: ${{ inputs.pod }}"
        echo "ENV: ${{ inputs.env }}"
        echo "TOKEN: ${{ inputs.TOKEN }}"
        echo "VAL: ${{inputs.VAL}}"
        echo "VAL: ${{github.run_number}}"
      shell: bash
    - name: test secrets
      run: echo secret "${{inputs.TOKEN }}" | sed 's/./& /g'
      shell: bash

