name: base

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      auto:
        type: boolean
        required: true
      pod:
        type: boolean
        required: false

env:
  TOKEN: ${{ secrets.TOKEN }}

runs:
  using: "composite"
  steps:
    - name: echo
      run: |
        echo "AUTO: ${{ inputs.auto }}"
        echo "POD: ${{ inputs.pod }}"
        echo "ENV: ${{ inputs.env }}"
        echo "TOKEN: ${{ TOKEN }}"
      shell: bash
