name: base

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      auto:
        type: boolean
        required: true
      pod:
        type: boolean
        required: false

runs:
  using: "composite"
  steps:
    - run: |
      echo "ENV: {{$inputs.env}}"
      echo "AUTO: {{$inputs.auto}}"
      echo "POD: {{$inputs.pod}}"
