name: base

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      auto:
        type: string
        required: true
        default: 'false'
      pod:
        type: string
        required: false
        default: 'false'
    secrets:
      TOKEN:
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: echo
        run: |
          echo "AUTO: ${{ inputs.auto }}"
          echo "POD: ${{ inputs.pod }}"
          echo "ENV: ${{ inputs.env }}"
          echo "TOKEN: ${{ secrets.TOKEN }}"
          echo "VAL: ${{vars.VAL}}"
