name: DEV

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        required: true
        options:
          - dev
          - stable
      auto:
        type: boolean
        required: true
      pod:
        type: boolean
        required: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: BUILD
        uses: ./.github/workflows/deploy
        with:
          env: ${{ github.event.inputs.env }}
          auto: ${{ github.event.inputs.auto }}
          pod: ${{ github.event.inputs.pod }}
          TOKEN: ${{ secrets.inherit }}
