name: DEV

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        required: true
        options:
          - dev
          - stable
      auto:
        type: boolean
        required: true
      pod:
        type: boolean
        required: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      env: ${{ github.event.inputs.env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  deploy-dev:
    name: DEPLOY
    needs: build
    if: ${{ needs.build.outputs.env == 'dev' || needs.build.outputs.env == 'stable'  }}
    steps:
      uses: ./.github/workflows/deploy
      with:
        env: ${{ github.event.inputs.env }}
        auto: ${{ github.event.inputs.auto }}
        pod: ${{ github.event.inputs.pod }}
      secrets: inherit
