name: DEV

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        required: true
        options:
          - dev
          - stable
      auto:
        type: boolean
        required: true
      pod:
        type: boolean
        required: false

jobs:
  integration:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ github.event.inputs.env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

deploy dev:
  name: DEPLOY
  needs: integration
  if: ${{ needs.integration.outputs.env == 'dev' || needs.integration.outputs.env == 'stable'  }}
  secrets: inherit
  uses: ./.github/workflows/deploy
  with:
    env: ${{ github.event.inputs.env }}
    auto: ${{ github.event.inputs.auto }}
    pod: ${{ github.event.inputs.pod }}
