name: DEV

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        required: true
        options:
          - dev
          - stable
      auto:
        type: boolean
        required: true
      pod:
        type: boolean
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/action.yml
    with:
      env: ${{ github.event.inputs.env }}
      auto: ${{ github.event.inputs.auto }}
      pod: ${{ github.event.inputs.pod }}
    secrets:
      TOKEN: ${{ secrets.TOKEN }}
