name: DEV

on:
  workflow_call:
    inputs:
      env:
        type: choice
        required: true
        options:
          - dev
      auto:
        type: boolean
        required: true
      pod:
        type: boolean
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/deploy.yml
        with:
          env: ${{ github.event.inputs.env }}
          auto: ${{ github.event.inputs.auto }}
          pod: ${{ github.event.inputs.pod }}
